name: Build and Deploy to EC2 via SSH1

on:
  push:
    branches: [main]  # Or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Pull docker image from hub
      run: sudo docker pull nginx:latest

    - name: Save Docker image to tar
      run: sudo docker save nginx:latest > my-app.tar

    - name: Upload Docker image to EC2 and deploy
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT || '22' }}
        source: "my-app.tar"
        target: "~/"

    - name: SSH into EC2 and load Docker image
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: ${{ secrets.EC2_PORT || '22' }}
        script: |
          sudo docker load < ~/my-app.tar
          sudo docker stop my-app1 || true
          sudo docker rm my-app1 || true
          sudo rm -rf < ~/my-app.tar
          sudo docker run -d --name my-app1 -p 81:80 nginx:latest
